### ISSUE TITLE
Players can’t respawn after dying (atm9nf)

### ISSUE THREAD

**Issue by Hibanan** [jpenilla/squaremap#293] opened 2024-09-11 15:51 UTC
Full log when this happens with multiple different players: https://paste2.org/7g4dvXLC

removing squaremap completely eliminated the problem.

Atm9 - no frills: version 0.1.15
Debian 12 host running graalvm ee java 17

**Comment by jpenilla** [comment] 2024-09-11 16:59
Duplicate of #284, #249, #201. Please use the search feature to check for duplicates before opening issues.

**Closed by jpenilla** 2024-09-11 16:59 UTC
Labels: duplicate

**Comment by Hibanan** [comment] 2024-09-11 17:01
You should probably have a warning that there are known game breaking bugs in your mods if you’re not willing to fix them. Cheers.
