### ISSUE TITLE
Map doesn't update 

### ISSUE THREAD

**Issue by protected22** [jpenilla/squaremap#81] opened 2022-10-18 04:52 UTC
Is there a way to get the map to update itself? It still shows buildings and places which already got changed some days ago my players in the world.

**Comment by jpenilla** [comment] 2023-01-05 22:20
By default, the map will update when things change, although change detection is most complete on Paper, some things might get missed on Fabric/Sponge. Are you still having this issue with squaremap 1.1.9? Locally everything seems to be working fine and I can't reproduce this.

**Comment by protected22** [comment] 2023-01-06 07:28
Hi. I believe it got fixed in 1.1.9. I notice it changes, but only after my server restarts. Probably something in Paper which causes that. But since my server now restarts every night, it isn't that much of a issue anymore.

**Comment by mxrtxn36** [comment] 2023-02-09 16:51
I use paper in 1.19.3 without any issues

**Comment by jpenilla** [comment] 2023-02-12 15:49
Reporter says their issue is solved, and issue has not been reproduced. Closing

**Closed by jpenilla** 2023-02-12 15:49 UTC
Labels: bug, unconfirmed

**Comment by Agaloth** [comment] 2023-07-27 11:53
This bug still happens to me, nothing is updating after the server has been up for more than 3 hours, the player list doesn't get updated either.
