### ISSUE TITLE
Only serve players.json through internal webserver

### ISSUE THREAD

**Issue by NyaomiDEV** [jpenilla/squaremap#278] opened 2024-08-23 15:45 UTC
I have an external webserver setup that is working with NGINX, however I'd like to have the internal server serving players.json as using the external server means that the file is flushed on disk every second or so. I could delay the flushing but it will make the map feel less "immersive and real time".

I'm therefore asking for a solution that is to never write the players.json file to disk and to serve it exclusively from the internal server, so that I can just reverse proxy to that and it would still work.

**Comment by jpenilla** [comment] 2024-08-23 18:50
At first glance, this seems like a duplicate of #224 which is resolved by #245

**Comment by NyaomiDEV** [comment] 2024-08-23 19:32
I don't know if that prevents the player.json to be written outright, because that's what I want. Also, I wanted a way to serve only that json in an API-like manner.

**Comment by jpenilla** [comment] 2024-10-11 20:46
This is practically solved by #245, you can have the internal server enabled and only proxy the players json to it.

**Closed by jpenilla** 2024-10-11 20:46 UTC
